version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: realtimeleaderboard
      POSTGRES_USER: modev
      POSTGRES_PASSWORD: zaq1@WSX
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://modev:zaq1@WSX@db:5432/realtimeleaderboard
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env

  celery:
    build: .
    command: celery -A Realtimeleaderboard worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://modev:zaq1@WSX@db:5432/realtimeleaderboard
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A Realtimeleaderboard beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://modev:zaq1@WSX@db:5432/realtimeleaderboard
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env

volumes:
  postgres_data:
